project:
  type: website
  resources: 
  - papers/*
  - files/*

website:
  title: "Max Kaufmann"
  google-analytics: "{{< var GOOGLE_ANALYTICS_KEY >}}"
  favicon: assets/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



